// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.32.0
// source: proto/postlike/postlike.proto

package postlike

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostLike struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId    int32                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId    string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *PostLike) Reset() {
	*x = PostLike{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_postlike_postlike_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostLike) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostLike) ProtoMessage() {}

func (x *PostLike) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postlike_postlike_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostLike.ProtoReflect.Descriptor instead.
func (*PostLike) Descriptor() ([]byte, []int) {
	return file_proto_postlike_postlike_proto_rawDescGZIP(), []int{0}
}

func (x *PostLike) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *PostLike) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PostLike) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreatePostLikeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId int32  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *CreatePostLikeRequest) Reset() {
	*x = CreatePostLikeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_postlike_postlike_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePostLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostLikeRequest) ProtoMessage() {}

func (x *CreatePostLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postlike_postlike_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostLikeRequest.ProtoReflect.Descriptor instead.
func (*CreatePostLikeRequest) Descriptor() ([]byte, []int) {
	return file_proto_postlike_postlike_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePostLikeRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CreatePostLikeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreatePostLikeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Postlike *PostLike `protobuf:"bytes,1,opt,name=postlike,proto3" json:"postlike,omitempty"`
}

func (x *CreatePostLikeResponse) Reset() {
	*x = CreatePostLikeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_postlike_postlike_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePostLikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostLikeResponse) ProtoMessage() {}

func (x *CreatePostLikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postlike_postlike_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostLikeResponse.ProtoReflect.Descriptor instead.
func (*CreatePostLikeResponse) Descriptor() ([]byte, []int) {
	return file_proto_postlike_postlike_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePostLikeResponse) GetPostlike() *PostLike {
	if x != nil {
		return x.Postlike
	}
	return nil
}

type FindAllPostLikesByPostIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId int32 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
}

func (x *FindAllPostLikesByPostIDRequest) Reset() {
	*x = FindAllPostLikesByPostIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_postlike_postlike_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllPostLikesByPostIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllPostLikesByPostIDRequest) ProtoMessage() {}

func (x *FindAllPostLikesByPostIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postlike_postlike_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllPostLikesByPostIDRequest.ProtoReflect.Descriptor instead.
func (*FindAllPostLikesByPostIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_postlike_postlike_proto_rawDescGZIP(), []int{3}
}

func (x *FindAllPostLikesByPostIDRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type FindAllPostLikesByPostIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Postlikes []*PostLike `protobuf:"bytes,1,rep,name=postlikes,proto3" json:"postlikes,omitempty"`
}

func (x *FindAllPostLikesByPostIDResponse) Reset() {
	*x = FindAllPostLikesByPostIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_postlike_postlike_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllPostLikesByPostIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllPostLikesByPostIDResponse) ProtoMessage() {}

func (x *FindAllPostLikesByPostIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postlike_postlike_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllPostLikesByPostIDResponse.ProtoReflect.Descriptor instead.
func (*FindAllPostLikesByPostIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_postlike_postlike_proto_rawDescGZIP(), []int{4}
}

func (x *FindAllPostLikesByPostIDResponse) GetPostlikes() []*PostLike {
	if x != nil {
		return x.Postlikes
	}
	return nil
}

type FindAllPostLikesByUserIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *FindAllPostLikesByUserIDRequest) Reset() {
	*x = FindAllPostLikesByUserIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_postlike_postlike_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllPostLikesByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllPostLikesByUserIDRequest) ProtoMessage() {}

func (x *FindAllPostLikesByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postlike_postlike_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllPostLikesByUserIDRequest.ProtoReflect.Descriptor instead.
func (*FindAllPostLikesByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_postlike_postlike_proto_rawDescGZIP(), []int{5}
}

func (x *FindAllPostLikesByUserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FindAllPostLikesByUserIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Postlikes []*PostLike `protobuf:"bytes,1,rep,name=postlikes,proto3" json:"postlikes,omitempty"`
}

func (x *FindAllPostLikesByUserIDResponse) Reset() {
	*x = FindAllPostLikesByUserIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_postlike_postlike_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllPostLikesByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllPostLikesByUserIDResponse) ProtoMessage() {}

func (x *FindAllPostLikesByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postlike_postlike_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllPostLikesByUserIDResponse.ProtoReflect.Descriptor instead.
func (*FindAllPostLikesByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_postlike_postlike_proto_rawDescGZIP(), []int{6}
}

func (x *FindAllPostLikesByUserIDResponse) GetPostlikes() []*PostLike {
	if x != nil {
		return x.Postlikes
	}
	return nil
}

type DeletePostLikeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId int32  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *DeletePostLikeRequest) Reset() {
	*x = DeletePostLikeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_postlike_postlike_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePostLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostLikeRequest) ProtoMessage() {}

func (x *DeletePostLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postlike_postlike_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostLikeRequest.ProtoReflect.Descriptor instead.
func (*DeletePostLikeRequest) Descriptor() ([]byte, []int) {
	return file_proto_postlike_postlike_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePostLikeRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *DeletePostLikeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeletePostLikeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeletePostLikeResponse) Reset() {
	*x = DeletePostLikeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_postlike_postlike_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePostLikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostLikeResponse) ProtoMessage() {}

func (x *DeletePostLikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postlike_postlike_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostLikeResponse.ProtoReflect.Descriptor instead.
func (*DeletePostLikeResponse) Descriptor() ([]byte, []int) {
	return file_proto_postlike_postlike_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePostLikeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_postlike_postlike_proto protoreflect.FileDescriptor

var file_proto_postlike_postlike_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x6c, 0x69, 0x6b, 0x65,
	0x2f, 0x70, 0x6f, 0x73, 0x74, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x70, 0x6f, 0x73, 0x74, 0x6c, 0x69, 0x6b, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x77, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x74,
	0x4c, 0x69, 0x6b, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x22, 0x49, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x4c,
	0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6f,
	0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6f, 0x73,
	0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x48, 0x0a, 0x16,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x74, 0x6c, 0x69,
	0x6b, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x6c,
	0x69, 0x6b, 0x65, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x08, 0x70, 0x6f,
	0x73, 0x74, 0x6c, 0x69, 0x6b, 0x65, 0x22, 0x3a, 0x0a, 0x1f, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c,
	0x6c, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x42, 0x79, 0x50, 0x6f, 0x73, 0x74,
	0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6f, 0x73,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74,
	0x49, 0x64, 0x22, 0x54, 0x0a, 0x20, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x73,
	0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x42, 0x79, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x74, 0x6c, 0x69,
	0x6b, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x6f, 0x73, 0x74,
	0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x09, 0x70,
	0x6f, 0x73, 0x74, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x22, 0x3a, 0x0a, 0x1f, 0x46, 0x69, 0x6e, 0x64,
	0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x42, 0x79, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x54, 0x0a, 0x20, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x50,
	0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x74,
	0x6c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x6f,
	0x73, 0x74, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x52,
	0x09, 0x70, 0x6f, 0x73, 0x74, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x22, 0x49, 0x0a, 0x15, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x32, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50,
	0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xc5, 0x04, 0x0a, 0x0f, 0x50, 0x6f,
	0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x71, 0x0a,
	0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x12,
	0x1f, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x20, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x16, 0x22, 0x11, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x3a, 0x01, 0x2a,
	0x12, 0x9b, 0x01, 0x0a, 0x18, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x74,
	0x4c, 0x69, 0x6b, 0x65, 0x73, 0x42, 0x79, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x12, 0x29, 0x2e,
	0x70, 0x6f, 0x73, 0x74, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c,
	0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x42, 0x79, 0x50, 0x6f, 0x73, 0x74, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x6c,
	0x69, 0x6b, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x4c,
	0x69, 0x6b, 0x65, 0x73, 0x42, 0x79, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x28, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x22, 0x12, 0x20, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x2f,
	0x70, 0x6f, 0x73, 0x74, 0x2f, 0x7b, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x7d, 0x12, 0x9b,
	0x01, 0x0a, 0x18, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69,
	0x6b, 0x65, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x29, 0x2e, 0x70, 0x6f,
	0x73, 0x74, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x50, 0x6f,
	0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x6c, 0x69, 0x6b,
	0x65, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b,
	0x65, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x28, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x22, 0x12, 0x20, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x2f, 0x7b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x7d, 0x12, 0x82, 0x01, 0x0a,
	0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x12,
	0x1f, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x20, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x2d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x27, 0x22, 0x25, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x2f, 0x7b, 0x70,
	0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x7d, 0x2f, 0x7b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x7d, 0x42, 0x10, 0x5a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x6c,
	0x69, 0x6b, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_postlike_postlike_proto_rawDescOnce sync.Once
	file_proto_postlike_postlike_proto_rawDescData = file_proto_postlike_postlike_proto_rawDesc
)

func file_proto_postlike_postlike_proto_rawDescGZIP() []byte {
	file_proto_postlike_postlike_proto_rawDescOnce.Do(func() {
		file_proto_postlike_postlike_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_postlike_postlike_proto_rawDescData)
	})
	return file_proto_postlike_postlike_proto_rawDescData
}

var file_proto_postlike_postlike_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_postlike_postlike_proto_goTypes = []interface{}{
	(*PostLike)(nil),                         // 0: postlike.PostLike
	(*CreatePostLikeRequest)(nil),            // 1: postlike.CreatePostLikeRequest
	(*CreatePostLikeResponse)(nil),           // 2: postlike.CreatePostLikeResponse
	(*FindAllPostLikesByPostIDRequest)(nil),  // 3: postlike.FindAllPostLikesByPostIDRequest
	(*FindAllPostLikesByPostIDResponse)(nil), // 4: postlike.FindAllPostLikesByPostIDResponse
	(*FindAllPostLikesByUserIDRequest)(nil),  // 5: postlike.FindAllPostLikesByUserIDRequest
	(*FindAllPostLikesByUserIDResponse)(nil), // 6: postlike.FindAllPostLikesByUserIDResponse
	(*DeletePostLikeRequest)(nil),            // 7: postlike.DeletePostLikeRequest
	(*DeletePostLikeResponse)(nil),           // 8: postlike.DeletePostLikeResponse
	(*timestamppb.Timestamp)(nil),            // 9: google.protobuf.Timestamp
}
var file_proto_postlike_postlike_proto_depIdxs = []int32{
	9, // 0: postlike.PostLike.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: postlike.CreatePostLikeResponse.postlike:type_name -> postlike.PostLike
	0, // 2: postlike.FindAllPostLikesByPostIDResponse.postlikes:type_name -> postlike.PostLike
	0, // 3: postlike.FindAllPostLikesByUserIDResponse.postlikes:type_name -> postlike.PostLike
	1, // 4: postlike.PostLikeService.CreatePostLike:input_type -> postlike.CreatePostLikeRequest
	3, // 5: postlike.PostLikeService.FindAllPostLikesByPostID:input_type -> postlike.FindAllPostLikesByPostIDRequest
	5, // 6: postlike.PostLikeService.FindAllPostLikesByUserID:input_type -> postlike.FindAllPostLikesByUserIDRequest
	7, // 7: postlike.PostLikeService.DeletePostLike:input_type -> postlike.DeletePostLikeRequest
	2, // 8: postlike.PostLikeService.CreatePostLike:output_type -> postlike.CreatePostLikeResponse
	4, // 9: postlike.PostLikeService.FindAllPostLikesByPostID:output_type -> postlike.FindAllPostLikesByPostIDResponse
	6, // 10: postlike.PostLikeService.FindAllPostLikesByUserID:output_type -> postlike.FindAllPostLikesByUserIDResponse
	8, // 11: postlike.PostLikeService.DeletePostLike:output_type -> postlike.DeletePostLikeResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_postlike_postlike_proto_init() }
func file_proto_postlike_postlike_proto_init() {
	if File_proto_postlike_postlike_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_postlike_postlike_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostLike); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_postlike_postlike_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePostLikeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_postlike_postlike_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePostLikeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_postlike_postlike_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllPostLikesByPostIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_postlike_postlike_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllPostLikesByPostIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_postlike_postlike_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllPostLikesByUserIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_postlike_postlike_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllPostLikesByUserIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_postlike_postlike_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePostLikeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_postlike_postlike_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePostLikeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_postlike_postlike_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_postlike_postlike_proto_goTypes,
		DependencyIndexes: file_proto_postlike_postlike_proto_depIdxs,
		MessageInfos:      file_proto_postlike_postlike_proto_msgTypes,
	}.Build()
	File_proto_postlike_postlike_proto = out.File
	file_proto_postlike_postlike_proto_rawDesc = nil
	file_proto_postlike_postlike_proto_goTypes = nil
	file_proto_postlike_postlike_proto_depIdxs = nil
}
