// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.32.0
// source: proto/comment/comment.proto

package comment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CommentServiceClient is the client API for CommentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommentServiceClient interface {
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error)
	FindCommentByID(ctx context.Context, in *FindCommentByIDRequest, opts ...grpc.CallOption) (*FindCommentByIDResponse, error)
	FindCommentsByPostID(ctx context.Context, in *FindCommentsByPostIDRequest, opts ...grpc.CallOption) (*FindCommentsByPostIDResponse, error)
	//	rpc FindCommentsByUserID(FindCommentsByUserIDRequest) returns (FindCommentsByUserIDResponse){
	//	  option (google.api.http) = {
	//	    get: "/api/v1/comments"
	//	  };
	//	}
	FindCommentsByParentID(ctx context.Context, in *FindCommentsByParentIDRequest, opts ...grpc.CallOption) (*FindCommentsByParentIDResponse, error)
	FindAllComments(ctx context.Context, in *FindAllCommentsRequest, opts ...grpc.CallOption) (*FindAllCommentsResponse, error)
	PatchComment(ctx context.Context, in *PatchCommentRequest, opts ...grpc.CallOption) (*PatchCommentResponse, error)
	DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error)
}

type commentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommentServiceClient(cc grpc.ClientConnInterface) CommentServiceClient {
	return &commentServiceClient{cc}
}

func (c *commentServiceClient) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error) {
	out := new(CreateCommentResponse)
	err := c.cc.Invoke(ctx, "/comment.CommentService/CreateComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceClient) FindCommentByID(ctx context.Context, in *FindCommentByIDRequest, opts ...grpc.CallOption) (*FindCommentByIDResponse, error) {
	out := new(FindCommentByIDResponse)
	err := c.cc.Invoke(ctx, "/comment.CommentService/FindCommentByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceClient) FindCommentsByPostID(ctx context.Context, in *FindCommentsByPostIDRequest, opts ...grpc.CallOption) (*FindCommentsByPostIDResponse, error) {
	out := new(FindCommentsByPostIDResponse)
	err := c.cc.Invoke(ctx, "/comment.CommentService/FindCommentsByPostID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceClient) FindCommentsByParentID(ctx context.Context, in *FindCommentsByParentIDRequest, opts ...grpc.CallOption) (*FindCommentsByParentIDResponse, error) {
	out := new(FindCommentsByParentIDResponse)
	err := c.cc.Invoke(ctx, "/comment.CommentService/FindCommentsByParentID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceClient) FindAllComments(ctx context.Context, in *FindAllCommentsRequest, opts ...grpc.CallOption) (*FindAllCommentsResponse, error) {
	out := new(FindAllCommentsResponse)
	err := c.cc.Invoke(ctx, "/comment.CommentService/FindAllComments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceClient) PatchComment(ctx context.Context, in *PatchCommentRequest, opts ...grpc.CallOption) (*PatchCommentResponse, error) {
	out := new(PatchCommentResponse)
	err := c.cc.Invoke(ctx, "/comment.CommentService/PatchComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceClient) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error) {
	out := new(DeleteCommentResponse)
	err := c.cc.Invoke(ctx, "/comment.CommentService/DeleteComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentServiceServer is the server API for CommentService service.
// All implementations must embed UnimplementedCommentServiceServer
// for forward compatibility
type CommentServiceServer interface {
	CreateComment(context.Context, *CreateCommentRequest) (*CreateCommentResponse, error)
	FindCommentByID(context.Context, *FindCommentByIDRequest) (*FindCommentByIDResponse, error)
	FindCommentsByPostID(context.Context, *FindCommentsByPostIDRequest) (*FindCommentsByPostIDResponse, error)
	//	rpc FindCommentsByUserID(FindCommentsByUserIDRequest) returns (FindCommentsByUserIDResponse){
	//	  option (google.api.http) = {
	//	    get: "/api/v1/comments"
	//	  };
	//	}
	FindCommentsByParentID(context.Context, *FindCommentsByParentIDRequest) (*FindCommentsByParentIDResponse, error)
	FindAllComments(context.Context, *FindAllCommentsRequest) (*FindAllCommentsResponse, error)
	PatchComment(context.Context, *PatchCommentRequest) (*PatchCommentResponse, error)
	DeleteComment(context.Context, *DeleteCommentRequest) (*DeleteCommentResponse, error)
	mustEmbedUnimplementedCommentServiceServer()
}

// UnimplementedCommentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCommentServiceServer struct {
}

func (UnimplementedCommentServiceServer) CreateComment(context.Context, *CreateCommentRequest) (*CreateCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedCommentServiceServer) FindCommentByID(context.Context, *FindCommentByIDRequest) (*FindCommentByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindCommentByID not implemented")
}
func (UnimplementedCommentServiceServer) FindCommentsByPostID(context.Context, *FindCommentsByPostIDRequest) (*FindCommentsByPostIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindCommentsByPostID not implemented")
}
func (UnimplementedCommentServiceServer) FindCommentsByParentID(context.Context, *FindCommentsByParentIDRequest) (*FindCommentsByParentIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindCommentsByParentID not implemented")
}
func (UnimplementedCommentServiceServer) FindAllComments(context.Context, *FindAllCommentsRequest) (*FindAllCommentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAllComments not implemented")
}
func (UnimplementedCommentServiceServer) PatchComment(context.Context, *PatchCommentRequest) (*PatchCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchComment not implemented")
}
func (UnimplementedCommentServiceServer) DeleteComment(context.Context, *DeleteCommentRequest) (*DeleteCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedCommentServiceServer) mustEmbedUnimplementedCommentServiceServer() {}

// UnsafeCommentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommentServiceServer will
// result in compilation errors.
type UnsafeCommentServiceServer interface {
	mustEmbedUnimplementedCommentServiceServer()
}

func RegisterCommentServiceServer(s grpc.ServiceRegistrar, srv CommentServiceServer) {
	s.RegisterService(&CommentService_ServiceDesc, srv)
}

func _CommentService_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comment.CommentService/CreateComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).CreateComment(ctx, req.(*CreateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentService_FindCommentByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindCommentByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).FindCommentByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comment.CommentService/FindCommentByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).FindCommentByID(ctx, req.(*FindCommentByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentService_FindCommentsByPostID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindCommentsByPostIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).FindCommentsByPostID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comment.CommentService/FindCommentsByPostID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).FindCommentsByPostID(ctx, req.(*FindCommentsByPostIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentService_FindCommentsByParentID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindCommentsByParentIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).FindCommentsByParentID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comment.CommentService/FindCommentsByParentID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).FindCommentsByParentID(ctx, req.(*FindCommentsByParentIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentService_FindAllComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).FindAllComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comment.CommentService/FindAllComments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).FindAllComments(ctx, req.(*FindAllCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentService_PatchComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).PatchComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comment.CommentService/PatchComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).PatchComment(ctx, req.(*PatchCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentService_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comment.CommentService/DeleteComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).DeleteComment(ctx, req.(*DeleteCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommentService_ServiceDesc is the grpc.ServiceDesc for CommentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "comment.CommentService",
	HandlerType: (*CommentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateComment",
			Handler:    _CommentService_CreateComment_Handler,
		},
		{
			MethodName: "FindCommentByID",
			Handler:    _CommentService_FindCommentByID_Handler,
		},
		{
			MethodName: "FindCommentsByPostID",
			Handler:    _CommentService_FindCommentsByPostID_Handler,
		},
		{
			MethodName: "FindCommentsByParentID",
			Handler:    _CommentService_FindCommentsByParentID_Handler,
		},
		{
			MethodName: "FindAllComments",
			Handler:    _CommentService_FindAllComments_Handler,
		},
		{
			MethodName: "PatchComment",
			Handler:    _CommentService_PatchComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _CommentService_DeleteComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/comment/comment.proto",
}
