// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.32.0
// source: proto/eventtag/eventtag.proto

package eventtag

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventTag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId   uint32 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TagId     uint32 `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	CreatedAt string `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt string `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *EventTag) Reset() {
	*x = EventTag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eventtag_eventtag_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTag) ProtoMessage() {}

func (x *EventTag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTag.ProtoReflect.Descriptor instead.
func (*EventTag) Descriptor() ([]byte, []int) {
	return file_proto_eventtag_eventtag_proto_rawDescGZIP(), []int{0}
}

func (x *EventTag) GetEventId() uint32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *EventTag) GetTagId() uint32 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *EventTag) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *EventTag) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateEventTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId uint32 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TagId   uint32 `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
}

func (x *CreateEventTagRequest) Reset() {
	*x = CreateEventTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eventtag_eventtag_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEventTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventTagRequest) ProtoMessage() {}

func (x *CreateEventTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventTagRequest.ProtoReflect.Descriptor instead.
func (*CreateEventTagRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventtag_eventtag_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEventTagRequest) GetEventId() uint32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *CreateEventTagRequest) GetTagId() uint32 {
	if x != nil {
		return x.TagId
	}
	return 0
}

type CreateEventTagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventTag *EventTag `protobuf:"bytes,1,opt,name=event_tag,json=eventTag,proto3" json:"event_tag,omitempty"`
}

func (x *CreateEventTagResponse) Reset() {
	*x = CreateEventTagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eventtag_eventtag_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEventTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventTagResponse) ProtoMessage() {}

func (x *CreateEventTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventTagResponse.ProtoReflect.Descriptor instead.
func (*CreateEventTagResponse) Descriptor() ([]byte, []int) {
	return file_proto_eventtag_eventtag_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEventTagResponse) GetEventTag() *EventTag {
	if x != nil {
		return x.EventTag
	}
	return nil
}

type FindByEventAndTagIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId uint32 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TagId   uint32 `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
}

func (x *FindByEventAndTagIDRequest) Reset() {
	*x = FindByEventAndTagIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eventtag_eventtag_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindByEventAndTagIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByEventAndTagIDRequest) ProtoMessage() {}

func (x *FindByEventAndTagIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByEventAndTagIDRequest.ProtoReflect.Descriptor instead.
func (*FindByEventAndTagIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventtag_eventtag_proto_rawDescGZIP(), []int{3}
}

func (x *FindByEventAndTagIDRequest) GetEventId() uint32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *FindByEventAndTagIDRequest) GetTagId() uint32 {
	if x != nil {
		return x.TagId
	}
	return 0
}

type FindByEventAndTagIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventTag *EventTag `protobuf:"bytes,1,opt,name=event_tag,json=eventTag,proto3" json:"event_tag,omitempty"`
}

func (x *FindByEventAndTagIDResponse) Reset() {
	*x = FindByEventAndTagIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eventtag_eventtag_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindByEventAndTagIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByEventAndTagIDResponse) ProtoMessage() {}

func (x *FindByEventAndTagIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByEventAndTagIDResponse.ProtoReflect.Descriptor instead.
func (*FindByEventAndTagIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_eventtag_eventtag_proto_rawDescGZIP(), []int{4}
}

func (x *FindByEventAndTagIDResponse) GetEventTag() *EventTag {
	if x != nil {
		return x.EventTag
	}
	return nil
}

type FindByEventIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId uint32 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
}

func (x *FindByEventIDRequest) Reset() {
	*x = FindByEventIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eventtag_eventtag_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindByEventIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByEventIDRequest) ProtoMessage() {}

func (x *FindByEventIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByEventIDRequest.ProtoReflect.Descriptor instead.
func (*FindByEventIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventtag_eventtag_proto_rawDescGZIP(), []int{5}
}

func (x *FindByEventIDRequest) GetEventId() uint32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type FindByEventIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventTags []*EventTag `protobuf:"bytes,1,rep,name=event_tags,json=eventTags,proto3" json:"event_tags,omitempty"`
}

func (x *FindByEventIDResponse) Reset() {
	*x = FindByEventIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eventtag_eventtag_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindByEventIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByEventIDResponse) ProtoMessage() {}

func (x *FindByEventIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByEventIDResponse.ProtoReflect.Descriptor instead.
func (*FindByEventIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_eventtag_eventtag_proto_rawDescGZIP(), []int{6}
}

func (x *FindByEventIDResponse) GetEventTags() []*EventTag {
	if x != nil {
		return x.EventTags
	}
	return nil
}

type FindByTagIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TagId uint32 `protobuf:"varint,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
}

func (x *FindByTagIDRequest) Reset() {
	*x = FindByTagIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eventtag_eventtag_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindByTagIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByTagIDRequest) ProtoMessage() {}

func (x *FindByTagIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByTagIDRequest.ProtoReflect.Descriptor instead.
func (*FindByTagIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventtag_eventtag_proto_rawDescGZIP(), []int{7}
}

func (x *FindByTagIDRequest) GetTagId() uint32 {
	if x != nil {
		return x.TagId
	}
	return 0
}

type FindByTagIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventTags []*EventTag `protobuf:"bytes,1,rep,name=event_tags,json=eventTags,proto3" json:"event_tags,omitempty"`
}

func (x *FindByTagIDResponse) Reset() {
	*x = FindByTagIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eventtag_eventtag_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindByTagIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByTagIDResponse) ProtoMessage() {}

func (x *FindByTagIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByTagIDResponse.ProtoReflect.Descriptor instead.
func (*FindByTagIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_eventtag_eventtag_proto_rawDescGZIP(), []int{8}
}

func (x *FindByTagIDResponse) GetEventTags() []*EventTag {
	if x != nil {
		return x.EventTags
	}
	return nil
}

type FindAllEventTagsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FindAllEventTagsRequest) Reset() {
	*x = FindAllEventTagsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eventtag_eventtag_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllEventTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllEventTagsRequest) ProtoMessage() {}

func (x *FindAllEventTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllEventTagsRequest.ProtoReflect.Descriptor instead.
func (*FindAllEventTagsRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventtag_eventtag_proto_rawDescGZIP(), []int{9}
}

type FindAllEventTagsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventTags []*EventTag `protobuf:"bytes,1,rep,name=event_tags,json=eventTags,proto3" json:"event_tags,omitempty"`
}

func (x *FindAllEventTagsResponse) Reset() {
	*x = FindAllEventTagsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eventtag_eventtag_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllEventTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllEventTagsResponse) ProtoMessage() {}

func (x *FindAllEventTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllEventTagsResponse.ProtoReflect.Descriptor instead.
func (*FindAllEventTagsResponse) Descriptor() ([]byte, []int) {
	return file_proto_eventtag_eventtag_proto_rawDescGZIP(), []int{10}
}

func (x *FindAllEventTagsResponse) GetEventTags() []*EventTag {
	if x != nil {
		return x.EventTags
	}
	return nil
}

type DeleteEventTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId uint32 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TagId   uint32 `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
}

func (x *DeleteEventTagRequest) Reset() {
	*x = DeleteEventTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eventtag_eventtag_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEventTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventTagRequest) ProtoMessage() {}

func (x *DeleteEventTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventTagRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventTagRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventtag_eventtag_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteEventTagRequest) GetEventId() uint32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *DeleteEventTagRequest) GetTagId() uint32 {
	if x != nil {
		return x.TagId
	}
	return 0
}

type DeleteEventTagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteEventTagResponse) Reset() {
	*x = DeleteEventTagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eventtag_eventtag_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEventTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventTagResponse) ProtoMessage() {}

func (x *DeleteEventTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventTagResponse.ProtoReflect.Descriptor instead.
func (*DeleteEventTagResponse) Descriptor() ([]byte, []int) {
	return file_proto_eventtag_eventtag_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteEventTagResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_eventtag_eventtag_proto protoreflect.FileDescriptor

var file_proto_eventtag_eventtag_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x74, 0x61, 0x67,
	0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x74, 0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x74, 0x61, 0x67, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7a, 0x0a, 0x08, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x54, 0x61, 0x67, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x15,
	0x0a, 0x06, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x74, 0x61, 0x67, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x22, 0x49, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x61, 0x67, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x61, 0x67, 0x49, 0x64, 0x22, 0x49,
	0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x5f, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x74, 0x61, 0x67, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x67, 0x52,
	0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x67, 0x22, 0x4e, 0x0a, 0x1a, 0x46, 0x69, 0x6e,
	0x64, 0x42, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x41, 0x6e, 0x64, 0x54, 0x61, 0x67, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x74, 0x61, 0x67, 0x49, 0x64, 0x22, 0x4e, 0x0a, 0x1b, 0x46, 0x69, 0x6e,
	0x64, 0x42, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x41, 0x6e, 0x64, 0x54, 0x61, 0x67, 0x49, 0x44,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x5f, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x74, 0x61, 0x67, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x67, 0x52,
	0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x67, 0x22, 0x31, 0x0a, 0x14, 0x46, 0x69, 0x6e,
	0x64, 0x42, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x4a, 0x0a, 0x15,
	0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74,
	0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x74, 0x61, 0x67, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x67, 0x52, 0x09, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x67, 0x73, 0x22, 0x2b, 0x0a, 0x12, 0x46, 0x69, 0x6e, 0x64,
	0x42, 0x79, 0x54, 0x61, 0x67, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15,
	0x0a, 0x06, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x74, 0x61, 0x67, 0x49, 0x64, 0x22, 0x48, 0x0a, 0x13, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x54,
	0x61, 0x67, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0a,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x74, 0x61, 0x67, 0x2e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x54, 0x61, 0x67, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x67, 0x73, 0x22,
	0x19, 0x0a, 0x17, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54,
	0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4d, 0x0a, 0x18, 0x46, 0x69,
	0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f,
	0x74, 0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x74, 0x61, 0x67, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x67, 0x52, 0x09,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x67, 0x73, 0x22, 0x49, 0x0a, 0x15, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x15, 0x0a,
	0x06, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74,
	0x61, 0x67, 0x49, 0x64, 0x22, 0x32, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x85, 0x06, 0x0a, 0x0f, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x54, 0x61, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x71, 0x0a, 0x0e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x67, 0x12, 0x1f,
	0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x74, 0x61, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x20, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x74, 0x61, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x16, 0x22, 0x11, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x67, 0x73, 0x3a, 0x01, 0x2a, 0x12,
	0x91, 0x01, 0x0a, 0x13, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x41,
	0x6e, 0x64, 0x54, 0x61, 0x67, 0x49, 0x44, 0x12, 0x24, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x74,
	0x61, 0x67, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x41, 0x6e,
	0x64, 0x54, 0x61, 0x67, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x74, 0x61, 0x67, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x41, 0x6e, 0x64, 0x54, 0x61, 0x67, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x27, 0x12, 0x25, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x67, 0x73, 0x2f,
	0x7b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x7d, 0x2f, 0x7b, 0x74, 0x61, 0x67, 0x5f,
	0x69, 0x64, 0x7d, 0x12, 0x7c, 0x0a, 0x0d, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x49, 0x44, 0x12, 0x1e, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x74, 0x61, 0x67, 0x2e,
	0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x74, 0x61, 0x67, 0x2e,
	0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x24, 0x12, 0x22, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x67, 0x73,
	0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2f, 0x7b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x7d, 0x12, 0x72, 0x0a, 0x0b, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x54, 0x61, 0x67, 0x49, 0x44,
	0x12, 0x1c, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x74, 0x61, 0x67, 0x2e, 0x46, 0x69, 0x6e, 0x64,
	0x42, 0x79, 0x54, 0x61, 0x67, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x74, 0x61, 0x67, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79,
	0x54, 0x61, 0x67, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x26, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x20, 0x12, 0x1e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x67, 0x73, 0x2f, 0x74, 0x61, 0x67, 0x2f, 0x7b, 0x74, 0x61,
	0x67, 0x5f, 0x69, 0x64, 0x7d, 0x12, 0x74, 0x0a, 0x10, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x67, 0x73, 0x12, 0x21, 0x2e, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x74, 0x61, 0x67, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x74, 0x61, 0x67, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x12, 0x11, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x67, 0x73, 0x12, 0x82, 0x01, 0x0a, 0x0e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x67, 0x12, 0x1f,
	0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x74, 0x61, 0x67, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x20, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x74, 0x61, 0x67, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x2d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x27, 0x2a, 0x25, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x67, 0x73, 0x2f, 0x7b, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x7d, 0x2f, 0x7b, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x7d,
	0x42, 0x10, 0x5a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x74,
	0x61, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_eventtag_eventtag_proto_rawDescOnce sync.Once
	file_proto_eventtag_eventtag_proto_rawDescData = file_proto_eventtag_eventtag_proto_rawDesc
)

func file_proto_eventtag_eventtag_proto_rawDescGZIP() []byte {
	file_proto_eventtag_eventtag_proto_rawDescOnce.Do(func() {
		file_proto_eventtag_eventtag_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_eventtag_eventtag_proto_rawDescData)
	})
	return file_proto_eventtag_eventtag_proto_rawDescData
}

var file_proto_eventtag_eventtag_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_eventtag_eventtag_proto_goTypes = []interface{}{
	(*EventTag)(nil),                    // 0: eventtag.EventTag
	(*CreateEventTagRequest)(nil),       // 1: eventtag.CreateEventTagRequest
	(*CreateEventTagResponse)(nil),      // 2: eventtag.CreateEventTagResponse
	(*FindByEventAndTagIDRequest)(nil),  // 3: eventtag.FindByEventAndTagIDRequest
	(*FindByEventAndTagIDResponse)(nil), // 4: eventtag.FindByEventAndTagIDResponse
	(*FindByEventIDRequest)(nil),        // 5: eventtag.FindByEventIDRequest
	(*FindByEventIDResponse)(nil),       // 6: eventtag.FindByEventIDResponse
	(*FindByTagIDRequest)(nil),          // 7: eventtag.FindByTagIDRequest
	(*FindByTagIDResponse)(nil),         // 8: eventtag.FindByTagIDResponse
	(*FindAllEventTagsRequest)(nil),     // 9: eventtag.FindAllEventTagsRequest
	(*FindAllEventTagsResponse)(nil),    // 10: eventtag.FindAllEventTagsResponse
	(*DeleteEventTagRequest)(nil),       // 11: eventtag.DeleteEventTagRequest
	(*DeleteEventTagResponse)(nil),      // 12: eventtag.DeleteEventTagResponse
}
var file_proto_eventtag_eventtag_proto_depIdxs = []int32{
	0,  // 0: eventtag.CreateEventTagResponse.event_tag:type_name -> eventtag.EventTag
	0,  // 1: eventtag.FindByEventAndTagIDResponse.event_tag:type_name -> eventtag.EventTag
	0,  // 2: eventtag.FindByEventIDResponse.event_tags:type_name -> eventtag.EventTag
	0,  // 3: eventtag.FindByTagIDResponse.event_tags:type_name -> eventtag.EventTag
	0,  // 4: eventtag.FindAllEventTagsResponse.event_tags:type_name -> eventtag.EventTag
	1,  // 5: eventtag.EventTagService.CreateEventTag:input_type -> eventtag.CreateEventTagRequest
	3,  // 6: eventtag.EventTagService.FindByEventAndTagID:input_type -> eventtag.FindByEventAndTagIDRequest
	5,  // 7: eventtag.EventTagService.FindByEventID:input_type -> eventtag.FindByEventIDRequest
	7,  // 8: eventtag.EventTagService.FindByTagID:input_type -> eventtag.FindByTagIDRequest
	9,  // 9: eventtag.EventTagService.FindAllEventTags:input_type -> eventtag.FindAllEventTagsRequest
	11, // 10: eventtag.EventTagService.DeleteEventTag:input_type -> eventtag.DeleteEventTagRequest
	2,  // 11: eventtag.EventTagService.CreateEventTag:output_type -> eventtag.CreateEventTagResponse
	4,  // 12: eventtag.EventTagService.FindByEventAndTagID:output_type -> eventtag.FindByEventAndTagIDResponse
	6,  // 13: eventtag.EventTagService.FindByEventID:output_type -> eventtag.FindByEventIDResponse
	8,  // 14: eventtag.EventTagService.FindByTagID:output_type -> eventtag.FindByTagIDResponse
	10, // 15: eventtag.EventTagService.FindAllEventTags:output_type -> eventtag.FindAllEventTagsResponse
	12, // 16: eventtag.EventTagService.DeleteEventTag:output_type -> eventtag.DeleteEventTagResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_eventtag_eventtag_proto_init() }
func file_proto_eventtag_eventtag_proto_init() {
	if File_proto_eventtag_eventtag_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_eventtag_eventtag_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventTag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eventtag_eventtag_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEventTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eventtag_eventtag_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEventTagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eventtag_eventtag_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindByEventAndTagIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eventtag_eventtag_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindByEventAndTagIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eventtag_eventtag_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindByEventIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eventtag_eventtag_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindByEventIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eventtag_eventtag_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindByTagIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eventtag_eventtag_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindByTagIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eventtag_eventtag_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllEventTagsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eventtag_eventtag_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllEventTagsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eventtag_eventtag_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteEventTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eventtag_eventtag_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteEventTagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_eventtag_eventtag_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_eventtag_eventtag_proto_goTypes,
		DependencyIndexes: file_proto_eventtag_eventtag_proto_depIdxs,
		MessageInfos:      file_proto_eventtag_eventtag_proto_msgTypes,
	}.Build()
	File_proto_eventtag_eventtag_proto = out.File
	file_proto_eventtag_eventtag_proto_rawDesc = nil
	file_proto_eventtag_eventtag_proto_goTypes = nil
	file_proto_eventtag_eventtag_proto_depIdxs = nil
}
