// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/message/message.proto

package messagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientEvent_Join
	//	*ClientEvent_Send
	Payload       isClientEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEvent) Reset() {
	*x = ClientEvent{}
	mi := &file_proto_message_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent) ProtoMessage() {}

func (x *ClientEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent.ProtoReflect.Descriptor instead.
func (*ClientEvent) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{0}
}

func (x *ClientEvent) GetPayload() isClientEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientEvent) GetJoin() *JoinRoom {
	if x != nil {
		if x, ok := x.Payload.(*ClientEvent_Join); ok {
			return x.Join
		}
	}
	return nil
}

func (x *ClientEvent) GetSend() *SendMessage {
	if x != nil {
		if x, ok := x.Payload.(*ClientEvent_Send); ok {
			return x.Send
		}
	}
	return nil
}

type isClientEvent_Payload interface {
	isClientEvent_Payload()
}

type ClientEvent_Join struct {
	Join *JoinRoom `protobuf:"bytes,1,opt,name=join,proto3,oneof"`
}

type ClientEvent_Send struct {
	Send *SendMessage `protobuf:"bytes,2,opt,name=send,proto3,oneof"`
}

func (*ClientEvent_Join) isClientEvent_Payload() {}

func (*ClientEvent_Send) isClientEvent_Payload() {}

type JoinRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint32                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // uuid string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoom) Reset() {
	*x = JoinRoom{}
	mi := &file_proto_message_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoom) ProtoMessage() {}

func (x *JoinRoom) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoom.ProtoReflect.Descriptor instead.
func (*JoinRoom) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{1}
}

func (x *JoinRoom) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *JoinRoom) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SendMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint32                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	SenderId      string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`          // uuid string
	SentAtUnix    int64                  `protobuf:"varint,4,opt,name=sent_at_unix,json=sentAtUnix,proto3" json:"sent_at_unix,omitempty"` // unix seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessage) Reset() {
	*x = SendMessage{}
	mi := &file_proto_message_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessage) ProtoMessage() {}

func (x *SendMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessage.ProtoReflect.Descriptor instead.
func (*SendMessage) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessage) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *SendMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *SendMessage) GetSentAtUnix() int64 {
	if x != nil {
		return x.SentAtUnix
	}
	return 0
}

type ServerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerEvent_Ack
	//	*ServerEvent_Delivered
	//	*ServerEvent_Error
	Payload       isServerEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_proto_message_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{3}
}

func (x *ServerEvent) GetPayload() isServerEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerEvent) GetAck() *StreamAck {
	if x != nil {
		if x, ok := x.Payload.(*ServerEvent_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ServerEvent) GetDelivered() *MessageDelivered {
	if x != nil {
		if x, ok := x.Payload.(*ServerEvent_Delivered); ok {
			return x.Delivered
		}
	}
	return nil
}

func (x *ServerEvent) GetError() *ErrorEvent {
	if x != nil {
		if x, ok := x.Payload.(*ServerEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isServerEvent_Payload interface {
	isServerEvent_Payload()
}

type ServerEvent_Ack struct {
	Ack *StreamAck `protobuf:"bytes,1,opt,name=ack,proto3,oneof"`
}

type ServerEvent_Delivered struct {
	Delivered *MessageDelivered `protobuf:"bytes,2,opt,name=delivered,proto3,oneof"`
}

type ServerEvent_Error struct {
	Error *ErrorEvent `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*ServerEvent_Ack) isServerEvent_Payload() {}

func (*ServerEvent_Delivered) isServerEvent_Payload() {}

func (*ServerEvent_Error) isServerEvent_Payload() {}

type StreamAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAck) Reset() {
	*x = StreamAck{}
	mi := &file_proto_message_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAck) ProtoMessage() {}

func (x *StreamAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAck.ProtoReflect.Descriptor instead.
func (*StreamAck) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{4}
}

func (x *StreamAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MessageDelivered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId        uint32                 `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	SenderId      string                 `protobuf:"bytes,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"` // uuid string
	CreatedAtUnix int64                  `protobuf:"varint,5,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageDelivered) Reset() {
	*x = MessageDelivered{}
	mi := &file_proto_message_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDelivered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDelivered) ProtoMessage() {}

func (x *MessageDelivered) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDelivered.ProtoReflect.Descriptor instead.
func (*MessageDelivered) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{5}
}

func (x *MessageDelivered) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MessageDelivered) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *MessageDelivered) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MessageDelivered) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *MessageDelivered) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

type ErrorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEvent) Reset() {
	*x = ErrorEvent{}
	mi := &file_proto_message_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEvent) ProtoMessage() {}

func (x *ErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEvent.ProtoReflect.Descriptor instead.
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{6}
}

func (x *ErrorEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_message_message_proto protoreflect.FileDescriptor

const file_proto_message_message_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/message/message.proto\x12\amessage\"m\n" +
	"\vClientEvent\x12'\n" +
	"\x04join\x18\x01 \x01(\v2\x11.message.JoinRoomH\x00R\x04join\x12*\n" +
	"\x04send\x18\x02 \x01(\v2\x14.message.SendMessageH\x00R\x04sendB\t\n" +
	"\apayload\"<\n" +
	"\bJoinRoom\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\rR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"y\n" +
	"\vSendMessage\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\rR\x06roomId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12 \n" +
	"\fsent_at_unix\x18\x04 \x01(\x03R\n" +
	"sentAtUnix\"\xa8\x01\n" +
	"\vServerEvent\x12&\n" +
	"\x03ack\x18\x01 \x01(\v2\x12.message.StreamAckH\x00R\x03ack\x129\n" +
	"\tdelivered\x18\x02 \x01(\v2\x19.message.MessageDeliveredH\x00R\tdelivered\x12+\n" +
	"\x05error\x18\x03 \x01(\v2\x13.message.ErrorEventH\x00R\x05errorB\t\n" +
	"\apayload\"%\n" +
	"\tStreamAck\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x94\x01\n" +
	"\x10MessageDelivered\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\rR\x06roomId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1b\n" +
	"\tsender_id\x18\x04 \x01(\tR\bsenderId\x12&\n" +
	"\x0fcreated_at_unix\x18\x05 \x01(\x03R\rcreatedAtUnix\"&\n" +
	"\n" +
	"ErrorEvent\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2H\n" +
	"\x0eMessageService\x126\n" +
	"\x04Chat\x12\x14.message.ClientEvent\x1a\x14.message.ServerEvent(\x010\x01B7Z5github.com/MingPV/ChatService/proto/message;messagepbb\x06proto3"

var (
	file_proto_message_message_proto_rawDescOnce sync.Once
	file_proto_message_message_proto_rawDescData []byte
)

func file_proto_message_message_proto_rawDescGZIP() []byte {
	file_proto_message_message_proto_rawDescOnce.Do(func() {
		file_proto_message_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_message_message_proto_rawDesc), len(file_proto_message_message_proto_rawDesc)))
	})
	return file_proto_message_message_proto_rawDescData
}

var file_proto_message_message_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_message_message_proto_goTypes = []any{
	(*ClientEvent)(nil),      // 0: message.ClientEvent
	(*JoinRoom)(nil),         // 1: message.JoinRoom
	(*SendMessage)(nil),      // 2: message.SendMessage
	(*ServerEvent)(nil),      // 3: message.ServerEvent
	(*StreamAck)(nil),        // 4: message.StreamAck
	(*MessageDelivered)(nil), // 5: message.MessageDelivered
	(*ErrorEvent)(nil),       // 6: message.ErrorEvent
}
var file_proto_message_message_proto_depIdxs = []int32{
	1, // 0: message.ClientEvent.join:type_name -> message.JoinRoom
	2, // 1: message.ClientEvent.send:type_name -> message.SendMessage
	4, // 2: message.ServerEvent.ack:type_name -> message.StreamAck
	5, // 3: message.ServerEvent.delivered:type_name -> message.MessageDelivered
	6, // 4: message.ServerEvent.error:type_name -> message.ErrorEvent
	0, // 5: message.MessageService.Chat:input_type -> message.ClientEvent
	3, // 6: message.MessageService.Chat:output_type -> message.ServerEvent
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_message_message_proto_init() }
func file_proto_message_message_proto_init() {
	if File_proto_message_message_proto != nil {
		return
	}
	file_proto_message_message_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientEvent_Join)(nil),
		(*ClientEvent_Send)(nil),
	}
	file_proto_message_message_proto_msgTypes[3].OneofWrappers = []any{
		(*ServerEvent_Ack)(nil),
		(*ServerEvent_Delivered)(nil),
		(*ServerEvent_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_message_message_proto_rawDesc), len(file_proto_message_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_message_message_proto_goTypes,
		DependencyIndexes: file_proto_message_message_proto_depIdxs,
		MessageInfos:      file_proto_message_message_proto_msgTypes,
	}.Build()
	File_proto_message_message_proto = out.File
	file_proto_message_message_proto_goTypes = nil
	file_proto_message_message_proto_depIdxs = nil
}
