// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.32.0
// source: proto/userreport/userreport.proto

package userreport

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Reporter string `protobuf:"bytes,2,opt,name=reporter,proto3" json:"reporter,omitempty"`
	ReportTo string `protobuf:"bytes,3,opt,name=report_to,json=reportTo,proto3" json:"report_to,omitempty"`
	Detail   string `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	Status   string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *UserReport) Reset() {
	*x = UserReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userreport_userreport_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReport) ProtoMessage() {}

func (x *UserReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userreport_userreport_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReport.ProtoReflect.Descriptor instead.
func (*UserReport) Descriptor() ([]byte, []int) {
	return file_proto_userreport_userreport_proto_rawDescGZIP(), []int{0}
}

func (x *UserReport) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserReport) GetReporter() string {
	if x != nil {
		return x.Reporter
	}
	return ""
}

func (x *UserReport) GetReportTo() string {
	if x != nil {
		return x.ReportTo
	}
	return ""
}

func (x *UserReport) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *UserReport) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateUserReportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reporter string `protobuf:"bytes,1,opt,name=reporter,proto3" json:"reporter,omitempty"`
	ReportTo string `protobuf:"bytes,2,opt,name=report_to,json=reportTo,proto3" json:"report_to,omitempty"`
	Detail   string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Status   string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CreateUserReportRequest) Reset() {
	*x = CreateUserReportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userreport_userreport_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReportRequest) ProtoMessage() {}

func (x *CreateUserReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userreport_userreport_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReportRequest.ProtoReflect.Descriptor instead.
func (*CreateUserReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_userreport_userreport_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserReportRequest) GetReporter() string {
	if x != nil {
		return x.Reporter
	}
	return ""
}

func (x *CreateUserReportRequest) GetReportTo() string {
	if x != nil {
		return x.ReportTo
	}
	return ""
}

func (x *CreateUserReportRequest) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *CreateUserReportRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateUserReportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserReport *UserReport `protobuf:"bytes,1,opt,name=user_report,json=userReport,proto3" json:"user_report,omitempty"`
}

func (x *CreateUserReportResponse) Reset() {
	*x = CreateUserReportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userreport_userreport_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReportResponse) ProtoMessage() {}

func (x *CreateUserReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userreport_userreport_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReportResponse.ProtoReflect.Descriptor instead.
func (*CreateUserReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_userreport_userreport_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserReportResponse) GetUserReport() *UserReport {
	if x != nil {
		return x.UserReport
	}
	return nil
}

type FindUserReportByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FindUserReportByIDRequest) Reset() {
	*x = FindUserReportByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userreport_userreport_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindUserReportByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserReportByIDRequest) ProtoMessage() {}

func (x *FindUserReportByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userreport_userreport_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserReportByIDRequest.ProtoReflect.Descriptor instead.
func (*FindUserReportByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_userreport_userreport_proto_rawDescGZIP(), []int{3}
}

func (x *FindUserReportByIDRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindUserReportByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserReport *UserReport `protobuf:"bytes,1,opt,name=user_report,json=userReport,proto3" json:"user_report,omitempty"`
}

func (x *FindUserReportByIDResponse) Reset() {
	*x = FindUserReportByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userreport_userreport_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindUserReportByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserReportByIDResponse) ProtoMessage() {}

func (x *FindUserReportByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userreport_userreport_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserReportByIDResponse.ProtoReflect.Descriptor instead.
func (*FindUserReportByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_userreport_userreport_proto_rawDescGZIP(), []int{4}
}

func (x *FindUserReportByIDResponse) GetUserReport() *UserReport {
	if x != nil {
		return x.UserReport
	}
	return nil
}

type FindAllByReporterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reporter string `protobuf:"bytes,1,opt,name=reporter,proto3" json:"reporter,omitempty"`
}

func (x *FindAllByReporterRequest) Reset() {
	*x = FindAllByReporterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userreport_userreport_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllByReporterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllByReporterRequest) ProtoMessage() {}

func (x *FindAllByReporterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userreport_userreport_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllByReporterRequest.ProtoReflect.Descriptor instead.
func (*FindAllByReporterRequest) Descriptor() ([]byte, []int) {
	return file_proto_userreport_userreport_proto_rawDescGZIP(), []int{5}
}

func (x *FindAllByReporterRequest) GetReporter() string {
	if x != nil {
		return x.Reporter
	}
	return ""
}

type FindAllByReporterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserReports []*UserReport `protobuf:"bytes,1,rep,name=user_reports,json=userReports,proto3" json:"user_reports,omitempty"`
}

func (x *FindAllByReporterResponse) Reset() {
	*x = FindAllByReporterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userreport_userreport_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllByReporterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllByReporterResponse) ProtoMessage() {}

func (x *FindAllByReporterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userreport_userreport_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllByReporterResponse.ProtoReflect.Descriptor instead.
func (*FindAllByReporterResponse) Descriptor() ([]byte, []int) {
	return file_proto_userreport_userreport_proto_rawDescGZIP(), []int{6}
}

func (x *FindAllByReporterResponse) GetUserReports() []*UserReport {
	if x != nil {
		return x.UserReports
	}
	return nil
}

type FindAllByReportToRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReportTo string `protobuf:"bytes,1,opt,name=report_to,json=reportTo,proto3" json:"report_to,omitempty"`
}

func (x *FindAllByReportToRequest) Reset() {
	*x = FindAllByReportToRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userreport_userreport_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllByReportToRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllByReportToRequest) ProtoMessage() {}

func (x *FindAllByReportToRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userreport_userreport_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllByReportToRequest.ProtoReflect.Descriptor instead.
func (*FindAllByReportToRequest) Descriptor() ([]byte, []int) {
	return file_proto_userreport_userreport_proto_rawDescGZIP(), []int{7}
}

func (x *FindAllByReportToRequest) GetReportTo() string {
	if x != nil {
		return x.ReportTo
	}
	return ""
}

type FindAllByReportToResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserReports []*UserReport `protobuf:"bytes,1,rep,name=user_reports,json=userReports,proto3" json:"user_reports,omitempty"`
}

func (x *FindAllByReportToResponse) Reset() {
	*x = FindAllByReportToResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userreport_userreport_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllByReportToResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllByReportToResponse) ProtoMessage() {}

func (x *FindAllByReportToResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userreport_userreport_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllByReportToResponse.ProtoReflect.Descriptor instead.
func (*FindAllByReportToResponse) Descriptor() ([]byte, []int) {
	return file_proto_userreport_userreport_proto_rawDescGZIP(), []int{8}
}

func (x *FindAllByReportToResponse) GetUserReports() []*UserReport {
	if x != nil {
		return x.UserReports
	}
	return nil
}

type FindAllUserReportsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FindAllUserReportsRequest) Reset() {
	*x = FindAllUserReportsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userreport_userreport_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllUserReportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllUserReportsRequest) ProtoMessage() {}

func (x *FindAllUserReportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userreport_userreport_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllUserReportsRequest.ProtoReflect.Descriptor instead.
func (*FindAllUserReportsRequest) Descriptor() ([]byte, []int) {
	return file_proto_userreport_userreport_proto_rawDescGZIP(), []int{9}
}

type FindAllUserReportsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserReports []*UserReport `protobuf:"bytes,1,rep,name=user_reports,json=userReports,proto3" json:"user_reports,omitempty"`
}

func (x *FindAllUserReportsResponse) Reset() {
	*x = FindAllUserReportsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userreport_userreport_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllUserReportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllUserReportsResponse) ProtoMessage() {}

func (x *FindAllUserReportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userreport_userreport_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllUserReportsResponse.ProtoReflect.Descriptor instead.
func (*FindAllUserReportsResponse) Descriptor() ([]byte, []int) {
	return file_proto_userreport_userreport_proto_rawDescGZIP(), []int{10}
}

func (x *FindAllUserReportsResponse) GetUserReports() []*UserReport {
	if x != nil {
		return x.UserReports
	}
	return nil
}

type PatchUserReportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Detail *string `protobuf:"bytes,2,opt,name=detail,proto3,oneof" json:"detail,omitempty"`
	Status *string `protobuf:"bytes,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
}

func (x *PatchUserReportRequest) Reset() {
	*x = PatchUserReportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userreport_userreport_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatchUserReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchUserReportRequest) ProtoMessage() {}

func (x *PatchUserReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userreport_userreport_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchUserReportRequest.ProtoReflect.Descriptor instead.
func (*PatchUserReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_userreport_userreport_proto_rawDescGZIP(), []int{11}
}

func (x *PatchUserReportRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PatchUserReportRequest) GetDetail() string {
	if x != nil && x.Detail != nil {
		return *x.Detail
	}
	return ""
}

func (x *PatchUserReportRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type PatchUserReportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserReport *UserReport `protobuf:"bytes,1,opt,name=user_report,json=userReport,proto3" json:"user_report,omitempty"`
}

func (x *PatchUserReportResponse) Reset() {
	*x = PatchUserReportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userreport_userreport_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatchUserReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchUserReportResponse) ProtoMessage() {}

func (x *PatchUserReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userreport_userreport_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchUserReportResponse.ProtoReflect.Descriptor instead.
func (*PatchUserReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_userreport_userreport_proto_rawDescGZIP(), []int{12}
}

func (x *PatchUserReportResponse) GetUserReport() *UserReport {
	if x != nil {
		return x.UserReport
	}
	return nil
}

type DeleteUserReportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteUserReportRequest) Reset() {
	*x = DeleteUserReportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userreport_userreport_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserReportRequest) ProtoMessage() {}

func (x *DeleteUserReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userreport_userreport_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserReportRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_userreport_userreport_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteUserReportRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteUserReportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteUserReportResponse) Reset() {
	*x = DeleteUserReportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userreport_userreport_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserReportResponse) ProtoMessage() {}

func (x *DeleteUserReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userreport_userreport_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserReportResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_userreport_userreport_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteUserReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_userreport_userreport_proto protoreflect.FileDescriptor

var file_proto_userreport_userreport_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x85, 0x01,
	0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x5f, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x54, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x82, 0x01, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x12, 0x1b, 0x0a,
	0x09, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x53, 0x0a, 0x18, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x72,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x22,
	0x2b, 0x0a, 0x19, 0x46, 0x69, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x55, 0x0a, 0x1a,
	0x46, 0x69, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x42, 0x79,
	0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0b, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x22, 0x36, 0x0a, 0x18, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x42, 0x79,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x22, 0x56, 0x0a, 0x19, 0x46,
	0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x42, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x73, 0x22, 0x37, 0x0a, 0x18, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x42, 0x79,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x6f, 0x22, 0x56, 0x0a, 0x19,
	0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x42, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0c, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x73, 0x22, 0x1b, 0x0a, 0x19, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x57, 0x0a, 0x1a, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x39, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x0b, 0x75,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x22, 0x78, 0x0a, 0x16, 0x50, 0x61,
	0x74, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x88, 0x01,
	0x01, 0x12, 0x1b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x01, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x88, 0x01, 0x01, 0x42, 0x09,
	0x0a, 0x07, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x52, 0x0a, 0x17, 0x50, 0x61, 0x74, 0x63, 0x68, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x37, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x0a, 0x75, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x29, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xc8, 0x07, 0x0a, 0x11, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x7d, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x23, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x72,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x22, 0x13, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f,
	0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x3a, 0x01, 0x2a, 0x12, 0x85,
	0x01, 0x0a, 0x12, 0x46, 0x69, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x42, 0x79, 0x49, 0x44, 0x12, 0x25, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x20, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x12, 0x18, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x91, 0x01, 0x0a, 0x11, 0x46, 0x69, 0x6e, 0x64, 0x41,
	0x6c, 0x6c, 0x42, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x12, 0x24, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c,
	0x6c, 0x42, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x25, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e,
	0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x42, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2f, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x29, 0x12, 0x27, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x2f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2f,
	0x7b, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x7d, 0x12, 0x92, 0x01, 0x0a, 0x11, 0x46,
	0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x42, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x6f,
	0x12, 0x24, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x46, 0x69,
	0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x42, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x42, 0x79, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x54, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x30, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x2a, 0x12, 0x28, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x2f, 0x72, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x54, 0x6f, 0x2f, 0x7b, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x74, 0x6f, 0x7d, 0x12,
	0x80, 0x01, 0x0a, 0x12, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x12, 0x25, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41,
	0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x12, 0x13, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x73, 0x12, 0x7f, 0x0a, 0x0f, 0x50, 0x61, 0x74, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x22, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x2e, 0x50, 0x61, 0x74, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x50, 0x61, 0x74, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x23,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1d, 0x32, 0x18, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f,
	0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d,
	0x3a, 0x01, 0x2a, 0x12, 0x7f, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x23, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x20, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x2a, 0x18, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x2f,
	0x7b, 0x69, 0x64, 0x7d, 0x42, 0x12, 0x5a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_userreport_userreport_proto_rawDescOnce sync.Once
	file_proto_userreport_userreport_proto_rawDescData = file_proto_userreport_userreport_proto_rawDesc
)

func file_proto_userreport_userreport_proto_rawDescGZIP() []byte {
	file_proto_userreport_userreport_proto_rawDescOnce.Do(func() {
		file_proto_userreport_userreport_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_userreport_userreport_proto_rawDescData)
	})
	return file_proto_userreport_userreport_proto_rawDescData
}

var file_proto_userreport_userreport_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_userreport_userreport_proto_goTypes = []interface{}{
	(*UserReport)(nil),                 // 0: userreport.UserReport
	(*CreateUserReportRequest)(nil),    // 1: userreport.CreateUserReportRequest
	(*CreateUserReportResponse)(nil),   // 2: userreport.CreateUserReportResponse
	(*FindUserReportByIDRequest)(nil),  // 3: userreport.FindUserReportByIDRequest
	(*FindUserReportByIDResponse)(nil), // 4: userreport.FindUserReportByIDResponse
	(*FindAllByReporterRequest)(nil),   // 5: userreport.FindAllByReporterRequest
	(*FindAllByReporterResponse)(nil),  // 6: userreport.FindAllByReporterResponse
	(*FindAllByReportToRequest)(nil),   // 7: userreport.FindAllByReportToRequest
	(*FindAllByReportToResponse)(nil),  // 8: userreport.FindAllByReportToResponse
	(*FindAllUserReportsRequest)(nil),  // 9: userreport.FindAllUserReportsRequest
	(*FindAllUserReportsResponse)(nil), // 10: userreport.FindAllUserReportsResponse
	(*PatchUserReportRequest)(nil),     // 11: userreport.PatchUserReportRequest
	(*PatchUserReportResponse)(nil),    // 12: userreport.PatchUserReportResponse
	(*DeleteUserReportRequest)(nil),    // 13: userreport.DeleteUserReportRequest
	(*DeleteUserReportResponse)(nil),   // 14: userreport.DeleteUserReportResponse
}
var file_proto_userreport_userreport_proto_depIdxs = []int32{
	0,  // 0: userreport.CreateUserReportResponse.user_report:type_name -> userreport.UserReport
	0,  // 1: userreport.FindUserReportByIDResponse.user_report:type_name -> userreport.UserReport
	0,  // 2: userreport.FindAllByReporterResponse.user_reports:type_name -> userreport.UserReport
	0,  // 3: userreport.FindAllByReportToResponse.user_reports:type_name -> userreport.UserReport
	0,  // 4: userreport.FindAllUserReportsResponse.user_reports:type_name -> userreport.UserReport
	0,  // 5: userreport.PatchUserReportResponse.user_report:type_name -> userreport.UserReport
	1,  // 6: userreport.UserReportService.CreateUserReport:input_type -> userreport.CreateUserReportRequest
	3,  // 7: userreport.UserReportService.FindUserReportByID:input_type -> userreport.FindUserReportByIDRequest
	5,  // 8: userreport.UserReportService.FindAllByReporter:input_type -> userreport.FindAllByReporterRequest
	7,  // 9: userreport.UserReportService.FindAllByReportTo:input_type -> userreport.FindAllByReportToRequest
	9,  // 10: userreport.UserReportService.FindAllUserReports:input_type -> userreport.FindAllUserReportsRequest
	11, // 11: userreport.UserReportService.PatchUserReport:input_type -> userreport.PatchUserReportRequest
	13, // 12: userreport.UserReportService.DeleteUserReport:input_type -> userreport.DeleteUserReportRequest
	2,  // 13: userreport.UserReportService.CreateUserReport:output_type -> userreport.CreateUserReportResponse
	4,  // 14: userreport.UserReportService.FindUserReportByID:output_type -> userreport.FindUserReportByIDResponse
	6,  // 15: userreport.UserReportService.FindAllByReporter:output_type -> userreport.FindAllByReporterResponse
	8,  // 16: userreport.UserReportService.FindAllByReportTo:output_type -> userreport.FindAllByReportToResponse
	10, // 17: userreport.UserReportService.FindAllUserReports:output_type -> userreport.FindAllUserReportsResponse
	12, // 18: userreport.UserReportService.PatchUserReport:output_type -> userreport.PatchUserReportResponse
	14, // 19: userreport.UserReportService.DeleteUserReport:output_type -> userreport.DeleteUserReportResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_userreport_userreport_proto_init() }
func file_proto_userreport_userreport_proto_init() {
	if File_proto_userreport_userreport_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_userreport_userreport_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userreport_userreport_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserReportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userreport_userreport_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserReportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userreport_userreport_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindUserReportByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userreport_userreport_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindUserReportByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userreport_userreport_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllByReporterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userreport_userreport_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllByReporterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userreport_userreport_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllByReportToRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userreport_userreport_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllByReportToResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userreport_userreport_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllUserReportsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userreport_userreport_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllUserReportsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userreport_userreport_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatchUserReportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userreport_userreport_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatchUserReportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userreport_userreport_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserReportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userreport_userreport_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserReportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_userreport_userreport_proto_msgTypes[11].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_userreport_userreport_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_userreport_userreport_proto_goTypes,
		DependencyIndexes: file_proto_userreport_userreport_proto_depIdxs,
		MessageInfos:      file_proto_userreport_userreport_proto_msgTypes,
	}.Build()
	File_proto_userreport_userreport_proto = out.File
	file_proto_userreport_userreport_proto_rawDesc = nil
	file_proto_userreport_userreport_proto_goTypes = nil
	file_proto_userreport_userreport_proto_depIdxs = nil
}
